name: CrystalWars
main: cn.lanink.crystalwars.CrystalWars
version: "0.1.0-SNAPSHOT"
api: ["1.0.9"]
load: POSTWORLD
authors: ["LT_Name", "iGxnon"]
depend:
  - "MemoriesOfTime-GameCore"

permissions:
  crystalwars.command.user:
    default: true
  crystalwars.command.admin:
    default: op